### ISSUE TITLE
Animation UI Component in your demo and my project is not the same

### ISSUE THREAD

**Issue by tranvansanghust** [DhafinFawwaz/Unity-AnimationUI#2]
When I add Animation UI component to my project, I got a difference version with your demo. Why is that? Please help me. Thanks
![image](https://github.com/DhafinFawwaz/Unity-AnimationUI/assets/32983505/ff0802ea-b850-4752-b61b-51ba5d59e388)

**Comment by DhafinFawwaz** [comment]
Can you tell me which Unity version you're using ? I need to try reproducing it.

**Comment by tranvansanghust** [comment]
I am using Unity 2021.3.4f1. But,  I resolved it by copied Assets folder to my project.

**Comment by DhafinFawwaz** [comment]
Alright nice, as long as the AnimationUI/Editor and AnimationUI/Script folder is present, it should be fine. You can delete the AnimationUI/Demo folder. Thanks for using the tool :)
