### ISSUE TITLE
PlayReversed will immediately trigger the OnAnimationEnded

### ISSUE THREAD

**Issue by sunsvip** [DhafinFawwaz/Unity-AnimationUI#9]
```
m_OpenAnimation.OnAnimationEnded = onAnimComplete.Invoke;
m_OpenAnimation.PlayReversed();

```

PlayReversed will immediately trigger the OnAnimationEnded callback method, rather than triggering it after the animation finishes playing.

**Comment by Marecom** [comment]
It seems that both PlayAnimation and PlayReversedAnimation have the same issue. The reason is that after StartCoroutine is called, the coroutine is immediately added to the _coroutines list, but it doesn't yield return to wait for the coroutine to complete.

**Comment by sunsvip** [comment]
> It seems that both PlayAnimation and PlayReversedAnimation have the same issue. The reason is that after StartCoroutine is called, the coroutine is immediately added to the _coroutines list, but it doesn't yield return to wait for the coroutine to complete.

Thank you, I implemented a similar feature based on DOTween. You can refer to: [https://github.com/sunsvip/GF_X/blob/master/Assets/AAAGame/Scripts/Common/DOTweenSequence.cs](https://github.com/sunsvip/GF_X/blob/master/Assets/AAAGame/Scripts/Common/DOTweenSequence.cs)
![preview](https://i-blog.csdnimg.cn/direct/fa0779008e7d4fd58083bd0a5b25e287.gif)
